Change pause while Docker restarts task to use wait_for
This task fails on gitlab-ci as it expects manual intervention and will fatal on the server that it is run on. The server is then skipped for all subsequent tasks necessitating re-running of kubespray on the stack

RUNNING HANDLER [docker : Docker | pause while Docker restarts] ****************
Thursday 23 November 2017  15:16:00 +0000 (0:00:05.111)       0:05:48.289 ***** 
Pausing for 10 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'str' object has no attribute 'buffer'
fatal: [feature-kubespray-etcd-2]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}


wait_for module works correctly